# Commands to setup client for testing
# $url = "https://raw.githubusercontent.com/ansible/ansible-documentation/main/examples/scripts/ConfigureRemotingForAnsible.ps1"
# $file = "$env:temp\ConfigureRemotingForAnsible.ps1"
# (New-Object -TypeName System.Net.WebClient).DownloadFile($url, $file)
# powershell.exe -ExecutionPolicy ByPass -File $file

---
- name: Windows Setup
  hosts: windows
  gather_facts: no

  tasks:
    - name: Create distribution directory
      ansible.windows.win_file:
        path: C:\Program Files\Mozilla Firefox\distribution
        state: directory

    - name: Download policies.json
      ansible.windows.win_get_url:
        url: https://raw.githubusercontent.com/mcwillster/pfsense-logger/refs/heads/main/Client/web-ext-artifacts/policies.json
        dest: C:\Program Files\Mozilla Firefox\distribution\policies.json

    - name: Download cert.pem
      ansible.windows.win_get_url:
        url: https://raw.githubusercontent.com/mcwillster/pfsense-logger/refs/heads/main/Client/web-ext-artifacts/cert.pem
        dest: C:\Program Files\Mozilla Firefox\distribution\cert.pem

    - name: Add cert to Windows library
          ansible.windows.win_powershell:
            script: |
              Import-Certificate -FilePath "C:\Program Files\Mozilla Firefox\distribution\cert.pem" -CertStoreLocation Cert:\LocalMachine\Root